### ISSUE TITLE
Elastic-Search optimieren

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#18]
Laggy bei Eingabe von i11102 in den Suchschlitz. Ggfs. Index neu erzeugen.

**Comment by hansendx** [comment]
The problem originated in the imported data.
Dataset data for i11102 contained value labels for every unique value. This caused i11102 to have a large number of value labels, since i11102 is numeric and has many unique values. The variable search evaluates value labels, making searches that related to i11102 very slow.
