### ISSUE TITLE
Verallgemeinerung Datenmodell: ein concept kann mehr topics haben

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/steering#5]
Use Cases:
- Es soll eine mehrfache Zuordnung in den aktuellen Topic-Baum vorgenommen werden, weil es keine inhaltlich eindeutige Zuordnung gibt.
- Die concepts (und damit die Variablen) sollen zusätzlich Themen in einem Replikationskalender (die in die Topic-Liste neu aufgenommen werden sollen) zugeordnet werden. [Damit würde sich verfestigen, dass die Topic-Liste studienspezifisch ist.]
- Es sollen andere inhaltliche Gruppierungen von concepts vorgenommen werden, wie hier http://companion.soep.de/Topics%20of%20SOEPcore/index.html#demography-and-population

**Comment by jgoebel** [comment]
Mit dem letzten Punkte werden die Topics dann aber mehr in eine Möglichkeit eine Gruppe von concepts zu beschreiben und werden dadurch zeitlich auch variabler.

**Comment by kwenzig** [comment]
Im Datenmodell ist dies wohl schon vorgesegehen. Tatsächlich wird topic-Liste als JSON-Blob imporiert. 

Weitere Schritte:

- Wie schauen Metadaten für die Use Cases exemplarisch aus?
- Wie sollen die Metadaten dargestellt werden?

**Comment by kwenzig** [comment]
Derzeit (https://github.com/kwenzig/soep-core/blob/master/metadata/concepts.csv) ist es so:

concept | topic | topic_prefix | label_de | label
----|----|----|----|----
_100_p_tim| t0901000000000000 | tim | beruf,lehre,nebenerw. std., so | hours sunday job, training
_1000_p_ila | t0802030000000000 | ila | entwicklung des lebensunterhaltskosten | developments in cost of living
_1001_p_ila | t0802030000000000 | ila | entwicklung d. reg. umweltsituation | developments in local environment

Künftig eine concepts.csv:

concept | label_de | label
----|----|----
_100_p_tim| beruf,lehre,nebenerw. std., so | hours sunday job, training
_1000_p_ila | entwicklung des lebensunterhaltskosten | developments in cost of living
_1001_p_ila | entwicklung d. reg. umweltsituation | developments in local environment

und eine concepts_topics.csv:

concept | topic 
----|----
_100_p_tim| tim
_1000_p_ila | ila 
_1001_p_ila | ila

Die topics bleiben hierarchisch organisiert. In sofern ändert sich an der Darstellung im Topic-Baum nichts.

Use-Case - zwei neue Äste im topic-Baum:
* bisheriger Ast
* Replikationskalender
* thematische Zuordnung im companion

Ein concept kann dann jedem Ast zugeordnet werden, Replikationskalender und Companion könnten dann auf ihre topics verlinken.

Replikationskalender (hinter dem Link finden sich zugeordnete Fragen):
![image](https://user-images.githubusercontent.com/6614820/73264076-3537ac00-41d2-11ea-8f63-d2cd03afff15.png)

Companion:
![image](https://user-images.githubusercontent.com/6614820/73264133-58faf200-41d2-11ea-848a-e6527eec452b.png)

**Comment by kwenzig** [comment]
Soll anhand einer concepts.csv getetstet werde, die mehrere Zeilen pro concept hat. Knut wird die erstellen.

**Comment by hansendx** [comment]
In addition to the files, that are delivered to the ./metadata/ folder:

- https://github.com/paneldata/soep-core/blob/master/ddionrails/topics.csv
- https://github.com/paneldata/soep-core/blob/master/ddionrails/concepts.csv

There is a third file, that is imported into the system:

- https://github.com/paneldata/soep-core/blob/master/ddionrails/topics.json

It is created from the other two files with this script: https://github.com/ddionrails/ddi.py/blob/master/ddi/onrails/repos/topics.py
The topics.json is imported "as is" into a JSON field in the database.
It is used to display the topic tree, whereas the content in the other files is used for everything else pertaining topics and concepts.
This might need refactoring, in order to accomplish the goal here.

TODO: look into creation of topics.json and import. Evaluate possible effort needed.
